services:
  - name: fastapi-backend
    type: web
    env: python
    plan: free  # Ensure you're on the free tier or choose another plan
    buildCommand: "poetry install"
    startCommand: "poetry run uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000
    autoDeploy: true

  - name: sveltekit-frontend
    type: web
    env: node
    plan: free  # Adjust as needed based on the size of your app.
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview -- --port 5000"
    envVars:
      - key: NODE_VERSION
        value: 20  # Ensure this matches your Node.js version.
