services:
  - name: fastapi-backend
    type: web
    env: python
    plan: free
    buildCommand: "cd backend && poetry install"
    # startCommand: "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    startCommand: "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - name: sveltekit-frontend
    type: web
    env: node
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run preview -- --port $PORT --host 0.0.0.0"

    envVars:
      - key: NODE_VERSION
        value: 20
